function randomArrayMember(a) {
  return a[Math.floor(Math.random()*a.length)];
}

tagline = {
  "adverbs" : [
    "selectively",
    "deliberately",
    "predominantly",
    "entirely",
    "fantastically",
    "improperly",
    "inexplicably",
    "lambastingly",
    "angioplastically",
    "crowmoundishly",
    "incapacitatingly",
    "bulldoggishly"
  ],

  "adjectives" : [
    "terrifying",
    "illogical",
    "preemininent",
    "mind-altering",
    "child-pulverizing",
    "soul-decanting",
    "water-divining",
    "condor-waffling",
    "mudhen-assailing",
    "rhododendron-abstracting",
    "Bobby-Fischer-defeating",
    "Ben-Kingsley-disarming",
    "parking-lot-obliterating",
    "UN-undermining",
    "mountain-goat-arbitrating",
    "diplomat-catapulting",
    "marmoset-confounding",
    "brick-laying",
    "crocodile-annihilating",
    "salary-cap-defying",
    "ostrich-ridiculing",
    "quantum",
    "digested",
    "revered",
    "ambivalent",
    "conscientious",
    "dastardly",
    "mundane",
    "cantankerous",
    "Rooster-Cogburn-indifferentiating",
    "egalitarian",
    "agro-touristic",
    "incapacitated",
    "intercontinental ballistic",
    "semi-conducting",
    "mongrel-unionizing",
    "agoraphobe-wrangling",
    "polyglot",
    "multitheistic",
    "monoglot",
    "meta-fungal"
  ],

  "nouns" : [
    "metatarsal",
    "dodecahedron",
    "Marmaduke",
    "gastropod",
    "rocketpants",
    "candy bean",
    "walrus brigade",
    "bastard shack",
    "lycanthrope",
    "ornithomimus",
    "Yul Brenner",
    "ikebana hut",
    "phantasmagoria",
    "idiomat",
    "thunderdome",
    "Olympiad",
    "mongoose",
    "narwhal",
    "ultrabuffalo",
    "crow philanthropist",
    "Confusatron",
    "knee genius",
    "Impostinator",
    "Argumentatron",
    "breakfastmaster",
    "burgomeister",
    "prawnvoy",
    "monkfish assassin",
    "calliope trebuchet"
  ]
};
