function randomArrayMember(a) {
  return a[Math.floor(Math.random()*a.length)];
}

tagline = {
  "adjectives" : [
    "terrifying",
    "illogical",
    "incongruous",
    "preemininent",
    "mind-altering",
    "child-pulverizing",
    "soul-decanting",
    "water-divining",
    "condor-waffling",
    "mudhen-assailing",
    "rhododendron-abstracting",
    "five-function",
    "fully-articulating",
    "Bobby-Fischer-defeating",
    "Ben-Kingsley-disarming",
    "parking-lot-obliterating",
    "UN-undermining",
    "yak-obliterating",
    "Inca-predating",
    "mountain-goat-arbitrating",
    "diplomat-catapulting",
    "marmoset-confounding",
    "brick-laying",
    "crocodile-annihilating",
    "salary-cap-defying",
    "ostrich-ridiculing",
    "quantum",
    "digested",
    "revered",
    "ambivalent",
    "conscientious",
    "dastardly",
    "mundane",
    "cantankerous",
    "Rooster-Cogburn-indifferentiating",
    "egalitarian",
    "agro-touristic",
    "incapacitated",
    "intercontinental ballistic",
    "semi-conducting",
    "mongrel-unionizing",
    "agoraphobe-wrangling",
    "polyglot",
    "multitheistic",
    "monoglot",
    "meta-fungal",
    "humpback",
    "inconceivable",
    "flabbergasting",
    "boulder-eating",
    "dorsal",
    "bloviated"
  ],

  "nouns" : [
    "metatarsal",
    "humon-wrangler",
    "dodecahedron",
    "Marmaduke",
    "weasel-colossus",
    "hypotenuse-walker",
    "contraband",
    "gastropod",
    "rocketpants",
    "candy bean",
    "walrus brigade",
    "eel hunter",
    "bastard shack",
    "lycanthrope",
    "ornithomimus",
    "Yul Brenner",
    "ikebana hut",
    "phantasmagoria",
    "idiomat",
    "thunderdome",
    "olympiad",
    "mongoose",
    "narwhal",
    "platinum anklet",
    "Rail-splitter",
    "ultrabuffalo",
    "crow philanthropist",
    "Confusatron",
    "knee genius",
    "Impostinator",
    "Argumentatron",
    "breakfastmaster",
    "burgomeister",
    "prawnvoy",
    "monkfish assassin",
    "calliope trebuchet"
  ]
};
