#!/bin/bash
app_name=mkzzn
tmp_path=/tmp/$app_name
remote_path=/var/www/mkzzn
remote_host=doblock

ssh $remote_host "echo 2>&1" || ssh-add ~/.ssh/`echo $app_name`_dsa
rm -rf $tmp_path
git clone mkzzn_github:mkzzn/$app_name.git $tmp_path
rsync -avz -e ssh $tmp_path $remote_host:$remote_path
